name: CI
on:
  pull_request:
  push:
jobs:
  code_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Scalafix check
        run: sbt "scalafixAll --check"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Build and Test
        run: sbt -v -Dfile.encoding=UTF-8 +test
